# Generated by Django 3.2.5 on 2021-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resume', models.FileField(upload_to='')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=240)),
                ('profile', models.ImageField(upload_to='profile_pic/')),
                ('title1', models.CharField(max_length=140)),
                ('titleLink1', models.CharField(max_length=240)),
                ('title2', models.CharField(max_length=140)),
                ('titleLink2', models.CharField(max_length=240)),
                ('title3', models.CharField(max_length=140)),
                ('titleLink3', models.CharField(max_length=240)),
                ('title4', models.CharField(max_length=140)),
                ('titleLink4', models.CharField(max_length=240)),
                ('title5', models.CharField(max_length=140)),
                ('titleLink5', models.CharField(max_length=240)),
                ('title6', models.CharField(max_length=140)),
                ('titleLink6', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=240)),
                ('detail', models.TextField()),
                ('source', models.CharField(max_length=140)),
                ('link', models.CharField(max_length=240)),
                ('badge', models.ImageField(upload_to='badges/')),
                ('badgeLink', models.CharField(default=None, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='EducationM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=240)),
                ('course', models.CharField(max_length=240)),
                ('duration', models.CharField(max_length=240)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=240)),
                ('designation', models.CharField(max_length=240)),
                ('duration', models.CharField(max_length=240)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IntouchM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illus', models.ImageField(upload_to='illustration')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='project/images/')),
                ('link', models.CharField(max_length=240)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=240)),
                ('cover_img', models.CharField(max_length=240)),
                ('level', models.CharField(max_length=240)),
                ('stars', models.IntegerField()),
                ('bg_color', models.CharField(max_length=240)),
            ],
        ),
    ]
