# Generated by Django 3.2.4 on 2021-06-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=240)),
                ('cover_img', models.ImageField(upload_to='skillsImg/')),
                ('level', models.CharField(max_length=240)),
                ('stars', models.IntegerField()),
                ('bg_color', models.CharField(max_length=240)),
            ],
        ),
    ]
