# Generated by Django 3.2.4 on 2021-06-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForModel', '0002_skillsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsm',
            name='cover_img',
            field=models.CharField(max_length=240),
        ),
    ]
