# Generated by Django 3.2.4 on 2021-06-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForModel', '0003_alter_skillsm_cover_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='project/images/')),
                ('link', models.CharField(max_length=240)),
                ('description', models.TextField()),
            ],
        ),
    ]
